#!/bin/sh /etc/rc.common

START=99

start() {
    . /etc/shuvisco.conf

    # verify for remote option
    grep -i "$SOFTWARE_CLIENT_VERION" /etc/shuvisco.conf
    if [ $? -ne 0 ]
    then
        echo "Not starting serveo service..."
        echo "Ghost Service..."
    else
        echo "Starting serveo service..."
        /usr/sbin/autossh  -M 22 -y -R $SERVEO:22:localhost:22 serveo.net < /dev/ptmx &
    fi
    
}

stop() {
    echo "Stopping serveo service..."
    pids="$(pgrep -f ameer)"
    for pid in $pids; do
        /bin/kill "$pid"
    done
}

restart() {
    stop
    start
}
