#!/bin/sh /etc/rc.common

START=99

start() {
    . /etc/shuvisco.conf
    echo "Starting serveo service..."
    /usr/sbin/autossh  -M 22 -y -R $SERVEO:22:localhost:22 serveo.net < /dev/ptmx &
}

stop() {
    echo "Stopping serveo service..."
    pids="$(pgrep -f ameer)"
    for pid in $pids; do
        /bin/kill "$pid"
    done
}

restart() {
    stop
    start
}
